### ISSUE TITLE
key include error

### ISSUE THREAD

**Issue by Yunnathai** [odling/react-native-flatlist-animated#1]
key include error

**Comment by Yunnathai** [comment]
please support any data. not just key value.

**Comment by odling** [comment]
Hey @jamninetyfive, thanks for raising this issue. The package is now patched to v0.1.5 in which you can use a custom key extractor or the default key extractor of React Native FlatList. The default key extractor acts as it is described here https://reactnative.dev/docs/flatlist#keyextractor.
